### ISSUE TITLE
[Legacy] Avoid duplicate CSS rules

### ISSUE THREAD

**Issue by Phixyn** [Phixyn/redhawk#32]
Consolidate rules by using multiple selectors e.g.

```css
#contact-form,
#contact-details {
    font-size: 1.2em;
}
```
